services:
  # Main Backend API Gateway
  backend:
    build: 
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - DEBUG=true
      - DB_SERVICE_URL=http://localhost:5001
      - ML_SERVICE_URL=http://localhost:5002
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - ML_SERVICE_URL=${ML_SERVICE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    networks:
      - timele-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - DEBUG=true
      - DB_SERVICE_URL=http://localhost:5001
      - ML_SERVICE_URL=http://localhost:5002
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - timele-network
    restart: unless-stopped

  ml:
    build:
      context: ./ml
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=/app
    ports:
      - "${ML_SERVICE_PORT}:${ML_SERVICE_PORT}"
    #depends_on:
    #  db:
    #    condition: service_healthy
    #  init-db:
    #    condition: service_completed_successfully
    volumes:
      - ./ml-service:/app
    networks:
      - timele-network
    restart: unless-stopped

networks:
  timele-network:
    driver: bridge
